const messages=document.querySelector('#messages'),filesInput=document.querySelector('#files'),attachments=document.querySelector('#attachments'),prompt=document.querySelector('#prompt');const API=window.SUPERME_API_URL||'http://localhost:3000';let token=localStorage.getItem('superme_token')||'',chats=[],current=[];
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function headers(){return {'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})}}async function api(url,opt={}){const r=await fetch(API+url,{...opt,headers:{...headers(),...(opt.headers||{})}});if(r.status===401){token='';localStorage.removeItem('superme_token');document.querySelector('#auth').style.display='flex'}return r}
async function login(e){e.preventDefault();const email=document.querySelector('#email').value,password=document.querySelector('#password').value;let r=await fetch(API+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(!r.ok)r=await fetch(API+'/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok){document.querySelector('#authMsg').textContent=d.error||'Xato';return}token=d.token;localStorage.setItem('superme_token',token);document.querySelector('#auth').style.display='none';await loadChats()}
function renderChats(){document.querySelector('#chatList').innerHTML=chats.map((c,i)=>`<div class="chat-item" onclick="loadChat(${i})">${esc(c.title||'Yangi chat')}</div>`).join('')}
function renderMessage(m){const w=document.createElement('div');w.className='message-row '+m.role;if(m.role==='assistant'){const a=document.createElement('div');a.className='avatar';a.textContent='✦';w.appendChild(a)}const d=document.createElement('div');d.className='msg '+m.role;d.textContent=m.text||'';w.appendChild(d);messages.appendChild(w);messages.scrollTop=messages.scrollHeight}
function newChat(){current=[];messages.innerHTML='<div class="welcome"><h1>Qanday yordam beray?</h1><p>Savol bering, kod yozdiring yoki loyiha yarating.</p></div>';showScreen('chat');prompt.focus()}
async function loadChats(){try{const r=await api('/api/chats');if(r.ok)chats=await r.json()}catch{}renderChats();document.querySelector('#auth').style.display=token?'none':'flex'}async function saveChats(){if(!current.length)return;const first=current.find(x=>x.role==='user');const item={title:(first?.text||'Yangi chat').replace(/\s+/g,' ').slice(0,45),messages:current};chats=[item,...chats.filter(x=>x.title!==item.title)].slice(0,200);renderChats();await api('/api/chats',{method:'POST',body:JSON.stringify({chats})})}function loadChat(i){current=chats[i]?.messages||[];messages.innerHTML='';current.forEach(renderMessage);showScreen('chat')}
function showFiles(){attachments.innerHTML='';[...filesInput.files].forEach(f=>{const c=document.createElement('div');c.className='chip';c.textContent=(f.type.startsWith('image/')?'🖼️ ':'📎 ')+f.name;attachments.appendChild(c)})}
async function sendMessage(e){e.preventDefault();const text=prompt.value.trim(),selected=[...filesInput.files];if(!text&&!selected.length)return;const user={role:'user',text:text+(selected.length?`\n[${selected.length} fayl]`:'')};current.push(user);renderMessage(user);prompt.value='';attachments.innerHTML='';filesInput.value='';const reply={role:'assistant',text:''};current.push(reply);renderMessage(reply);const bubble=messages.lastChild.querySelector('.msg');try{const images=[];for(const f of selected.filter(x=>x.type.startsWith('image/')).slice(0,10))images.push(await dataUrl(f));const r=await api('/api/chat/stream',{method:'POST',body:JSON.stringify({messages:current.slice(0,-1),images})});if(!r.ok){const d=await r.json();throw Error(d.error||'Backend xatosi')}const rd=r.body.getReader(),dec=new TextDecoder();let buf='';while(true){const {value,done}=await rd.read();if(done)break;buf+=dec.decode(value,{stream:true});const parts=buf.split('\n\n');buf=parts.pop()||'';for(const p of parts){const line=p.split('\n').find(x=>x.startsWith('data: '));if(!line)continue;const d=JSON.parse(line.slice(6));if(d.type==='delta'){reply.text+=d.text;bubble.textContent=reply.text}if(d.type==='error')throw Error(d.error)}}}catch(e){reply.text='⚠️ '+e.message;bubble.textContent=reply.text}await saveChats()}
function dataUrl(f){return new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(f)})}
function startVoice(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){prompt.placeholder='Brauzer voice recognitionni qo‘llamaydi';return}const r=new R();r.lang='uz-UZ';r.interimResults=false;r.onresult=e=>{prompt.value=e.results[0][0].transcript};r.start()}
async function startBuild(){const result=document.querySelector('#buildResult');result.textContent='⏳ Build...';try{const r=await api('/api/build',{method:'POST',body:JSON.stringify({target:document.querySelector('#buildTarget').value,artifact_name:document.querySelector('#artifactName').value.trim()||'superme-ai-build'})});const d=await r.json();result.textContent=r.ok?'✅ '+d.message:'❌ '+d.error}catch(e){result.textContent='❌ '+e.message}}
function showScreen(n){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.querySelector('#'+n+'Screen').classList.add('active');const t={chat:['SUPERME AI','AI assistant'],build:['Build Agent','Workspace + GitHub'],secrets:['Secrets','Environment']}[n];document.querySelector('#screenTitle').textContent=t[0];document.querySelector('#screenSub').textContent=t[1];if(n==='secrets')loadSecretStatus()}
async function loadSecretStatus(){try{const d=await(await api('/api/config/status')).json();document.querySelector('#openaiStatus').textContent=d.openai?'✅ Ulangan':'❌ Yo‘q';document.querySelector('#telegramStatus').textContent=d.telegram?'✅ Ulangan':'❌ Yo‘q';document.querySelector('#githubStatus').textContent=d.githubBuild?'✅ Ulangan':'❌ Yo‘q'}catch{}}async function testTelegram(){const r=await api('/api/telegram/test',{method:'POST'});document.querySelector('#secretResult').textContent=r.ok?'✅ Telegram ishlayapti':'❌ Telegram xatosi'}
loadChats();