const messages=document.querySelector('#messages');const filesInput=document.querySelector('#files');const attachments=document.querySelector('#attachments');const prompt=document.querySelector('#prompt');let chats=JSON.parse(localStorage.getItem('superme_chats')||'[]');let current=[];
function renderChats(){document.querySelector('#chatList').innerHTML=chats.map((c,i)=>`<div class="chat-item" onclick="loadChat(${i})">${escapeHtml(c.title||'Yangi chat')}</div>`).join('')}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function newChat(){saveChat();current=[];messages.innerHTML='<div class="welcome"><h1>Qanday yordam beray?</h1><p>Rasm, video, fayl yuboring yoki savolingizni yozing.</p></div>';renderChats()}
function saveChat(){if(!current.length)return;chats.unshift({title:current.find(x=>x.role==='user')?.text?.slice(0,35)||'Yangi chat',messages:current});chats=chats.slice(0,100);localStorage.setItem('superme_chats',JSON.stringify(chats))}
function loadChat(i){current=chats[i].messages||[];messages.innerHTML='';current.forEach(renderMessage)}
function renderMessage(m){const d=document.createElement('div');d.className='msg '+m.role;d.textContent=m.text||'';messages.appendChild(d);messages.scrollTop=messages.scrollHeight}
function showFiles(){attachments.innerHTML='';[...filesInput.files].forEach(f=>{const c=document.createElement('div');c.className='chip';c.textContent=`${f.type.startsWith('image/')?'🖼️':f.type.startsWith('video/')?'🎥':'📎'} ${f.name}`;attachments.appendChild(c)})}
function sendMessage(e){e.preventDefault();const text=prompt.value.trim();const selected=[...filesInput.files];if(!text&&!selected.length)return;const label=text+(selected.length?`\n[${selected.length} ta fayl biriktirildi]`:'');const m={role:'user',text:label};current.push(m);renderMessage(m);prompt.value='';attachments.innerHTML='';filesInput.value='';const reply={role:'assistant',text:'SUPERME AI backend ulanadigan joy tayyor. Bu frontend fayllarni ko‘p tanlash va chatga biriktirishni qo‘llab-quvvatlaydi.'};current.push(reply);renderMessage(reply);saveChat();renderChats()}
renderChats();